### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by kseo** [fsharp/FSharp.Data#823]
The following code no longer compiles after upgrading Mono version to 4.0.0.

    open FSharp.Data
    type Message = JsonProvider<""" {"Timestamp":"2015-04-06T20:17:13"} """>

/Users/kseo/Projects/FSharpDataTest/FSharpDataTest/Program.fs(6,16): error FS3033: The type provider 'ProviderImplementation.JsonProvider' reported an error: Object reference not set to an instance of an object

**Comment by dmaxime** [comment]
I got a very similar error with the CsvProvider on Mono 4.0. Using a tab-delimited file (sample.tsv) containing a date column: 
```
id	request_date
1061	2014-12-09
1145	2014-12-09
1146	2014-12-09
1062	2014-12-09
1147	2014-12-09
1148	2014-12-09
1063	2014-12-09
1149	2014-12-09
1064	2014-12-09
```

The following code breaks
```
open FSharp.Data
let sample = CsvProvider<"sample.tsv", HasHeaders=true >.GetSample()
```
error FS3033: The type provider 'ProviderImplementation.CsvProvider' reported an error: Object reference not set to an instance of an object


while this one works fine:
```
open FSharp.Data
let sample = CsvProvider<"sample.tsv", HasHeaders=true, Schema="request_date=date" >.GetSample()
```

It seems the CsvProvider has issues guessing date column types on Mono. Specifying the `date` type in the schema solves the issue.

**Comment by ovatsus** [comment]
Can you attach debugger and check where the null is coming from?

**Comment by dmaxime** [comment]
Code does not even compile and I do not know how to attach a debugger to
the compilation process. Would you have any link showing how to do this?

Or is there a way to make this code compile and have the error appear at
the execution time?

2015-05-11 16:40 GMT-07:00 Gustavo Guerra <notifications@github.com>:

**Comment by andrevdm** [comment]
I can replicate with this example
    ```F#
    type t = JsonProvider<"""{"d":"2015-05-19T10:00:00.000Z"}""">
    ````
I'll try debug ASAP

**Comment by brianary** [comment]
I'm unable to use FSharp.Data at all in Visual Studio 2013 Update 4.

Running:

    #I @"C:\tools\FSharp.Data\lib\net40"
    #r "FSharp.Data"

Results in:

    Microsoft (R) F# Interactive version 12.0.30815.0
    Copyright (c) Microsoft Corporation. All Rights Reserved.
    
    For help type #help;;
    
    > 
    
    --> Added 'C:\tools\FSharp.Data\lib\net40' to library include path
    
    ~vs77C9.fsx(2,1): error FS3053: The type provider 'ProviderImplementation.JsonProvider' reported an error: The type provider constructor has thrown an exception: Object reference not set to an instance of an object.
    >

**Comment by andrevdm** [comment]
@brianary is there any chance you can debug it? Debug studio with another instance of studio. (See e.g.http://blog.ctaggart.com/2014/07/debugging-into-f-type-provider-source.html?m=1). I think that will really help the team and thoes of us waiting for a fix :-)

**Comment by brianary** [comment]
@andrevdm It looks like AssemblyResolver.fs:138:

    WebRequest.DefaultWebProxy.Credentials <- CredentialCache.DefaultNetworkCredentials

In the caught exception, it's:

    System.NullReferenceException was unhandled by user code
    Message: An exception of type 'System.NullReferenceException' occurred in FSharp.Data.DesignTime.dll but was not handled in user code
    Additional information: Object reference not set to an instance of an object.

**Comment by ovatsus** [comment]
A pull request to workaround this would be welcomed!

**Comment by pcubeddev** [comment]
I think I've found it, its this line in StructuralInference.fs

  let abbreviatedEraNames = cultureInfo.Calendar.GetType().GetProperty("AbbreviatedEraNames", Reflection.BindingFlags.Instance ||| Reflection.BindingFlags.NonPublic).GetValue(cultureInfo.Calendar, [| |]) :?> string[]

It looks like with .net +4.5 the reflection to get AbbreviatedEraNames is breaking. For +4.5 you can call cultureInfo.DateTimeFormat.GetAbbreviatedEraName(era) directly.

I don't know the history of this method but I'll send a pull request with a working fix shortly.

Andre

**Comment by andrevdm** [comment]
I think I've found it, its this line in StructuralInference.fs

let abbreviatedEraNames = cultureInfo.Calendar.GetType().GetProperty("AbbreviatedEraNames", Reflection.BindingFlags.Instance ||| Reflection.BindingFlags.NonPublic).GetValue(cultureInfo.Calendar, [| |]) :?> string[]

It looks like with .net +4.5 the reflection to get AbbreviatedEraNames is breaking. For +4.5 you can call cultureInfo.DateTimeFormat.GetAbbreviatedEraName(era) directly.

I don't know the history of this method but I'll send a pull request with a working fix shortly.

Andre

**Comment by tpetricek** [comment]
I submitted a fix for this in #840
